### ISSUE TITLE
Issue 남겨주시면 해결해보겠습니다~

### ISSUE THREAD

**Issue by ShipFriend0516** [ShipFriend0516/Primitive#10]
Issue 많이 남겨주세요

**Comment by BinarySstar** [comment]
**소개 페이지를 제외한 모든 페이지**에서 F5 또는 새로고침 시 에러 페이지 발생.
![image](https://github.com/ShipFriend0516/Primitive/assets/117090689/b0d2bc52-f0be-407e-8ec5-06af60c5b81f)

**Comment by ShipFriend0516** [comment]
해결했습니다.. 이슈제보 감사드려요!! 다음에는 새 이슈 만들기로 만들어주시면 됩니다. 😎👍
